### PR TITLE
feat: add further optimizations to colors

### PR DESCRIPTION
**Pull request by Lash-L**
This precompiles room colors and just color colors so that we can know that they exist and access the property directly.

I tried to make sure this would not be a breaking change.

### CODE REVIEW

**Comment by Lash-L** [comment]
@PiotrMachowski tagging you as it didn't allow me to assign you and I know how easy it is to miss something like this.

**Comment by PiotrMachowski** [comment]
@Lash-L I'll try to merge all your PRs soon 👍

**Comment by Lash-L** [comment]
No rush! Just wanted to make sure you saw it

**Comment by Lash-L** [comment]
I would like to include these optimizations in the 2024.5 release along with some others I've done for how I do maps. No super rush, and if you're too busy to get it done by then, no worries

**Comment by PiotrMachowski** [comment]
I was out for a month. I hoped that I will have some to merge it, but it was not doable. Now I'm back and will take care of this 👍

**Comment by PiotrMachowski** [comment]
Thanks @Lash-L, I have finally merged and released it 👍

**Comment by Lash-L** [comment]
> Thanks @Lash-L, I have finally merged and released it 👍

Thanks @PiotrMachowski !

**Pull request merged**
